#!/usr/bin/env python3
"""
miniShell test runner.

Every expectation in expected.txt was produced by a real shell (dash, or
bash for the handful of cases where dash's exit codes are its own), never
by miniShell.  That is the point: the suite can fail.

  ./run.py ../minishell              compare against the recorded expectations
  ./run.py ../minishell --regen      regenerate expectations from the reference shells
  ./run.py ../minishell --ref        compare against the reference shells live
  ./run.py ../minishell --verbose    show every case, not just failures
"""

import os
import subprocess
import sys
import tempfile
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
CASES = os.path.join(HERE, "cases.txt")
EXPECTED = os.path.join(HERE, "expected.txt")

REF_PATHS = {
    "dash": ["/usr/bin/dash", "/bin/dash"],
    "bash": ["/usr/bin/bash", "/bin/bash"],
}


def find_ref(name):
    for p in REF_PATHS.get(name, []):
        if os.path.exists(p):
            return p
    return None


def load_cases(path):
    cases = []
    cur = None
    for raw in open(path):
        line = raw.rstrip("\n")
        if cur is None:
            if line.startswith("@name "):
                cur = {"name": line[6:], "ref": "dash", "note": None, "script": []}
            continue
        if line.startswith("@ref "):
            cur["ref"] = line[5:].strip()
            continue
        if line.startswith("@note "):
            cur["note"] = line[6:]
            continue
        if line == "@@":
            cur["script"] = "\n".join(cur["script"])
            cases.append(cur)
            cur = None
            continue
        cur["script"].append(line)
    return cases


def load_expected(path):
    exp = {}
    name = None
    rc = None
    out = []
    for raw in open(path):
        line = raw.rstrip("\n")
        if name is None:
            if line.startswith("@name "):
                name = line[6:]
            continue
        if line.startswith("@rc "):
            rc = int(line[4:])
            continue
        if line == "@@":
            exp[name] = (("\n".join(out) + "\n") if out else "", rc)
            name, rc, out = None, None, []
            continue
        out.append(line)
    return exp


def run_shell(shell, script, tmp):
    env = dict(os.environ)
    env["MSH_TMP"] = tmp
    env["HOME"] = tmp
    env["LC_ALL"] = "C"
    for k in ("IFS", "PS1", "PS2", "PS4", "S", "Q", "V", "X", "Y", "Z"):
        env.pop(k, None)

    path = os.path.join(tmp, "case.sh")
    with open(path, "w") as f:
        f.write(script + "\n")

    try:
        p = subprocess.run([shell, path], capture_output=True, timeout=20,
                           text=True, errors="replace", env=env,
                           stdin=subprocess.DEVNULL, cwd=tmp)
        out, err = p.stdout, p.stderr
    except subprocess.TimeoutExpired:
        return "<<TIMEOUT>>", -99

    # A sanitiser writes to stderr, and stderr is not compared - so without
    # this a leak or an overflow would sail past a passing test.
    for marker in ("Sanitizer", "runtime error:", "LeakSanitizer"):
        if marker in err:
            return "<<SANITIZER>>\n" + err[:1500], -98

    return out, p.returncode


def with_tmp(fn):
    tmp = tempfile.mkdtemp(prefix="mshtest.")
    try:
        return fn(tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def regen(cases):
    missing = set()
    with open(EXPECTED, "w") as f:
        f.write("# Generated by run.py --regen from the reference shells named\n"
                "# in cases.txt.  Do not hand-edit: regenerate instead.\n\n")
        for c in cases:
            ref = find_ref(c["ref"])
            if not ref:
                missing.add(c["ref"])
                continue
            out, rc = with_tmp(lambda t: run_shell(ref, c["script"], t))
            f.write("@name %s\n@rc %d\n" % (c["name"], rc))
            if out:
                f.write(out if out.endswith("\n") else out + "\n")
            f.write("@@\n")
    if missing:
        print("warning: reference shell(s) not installed: %s" % ", ".join(sorted(missing)))
    print("regenerated %d expectations" % len(cases))


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2

    shell = os.path.abspath(sys.argv[1])
    flags = sys.argv[2:]
    cases = load_cases(CASES)

    if "--regen" in flags:
        regen(cases)
        return 0

    live = "--ref" in flags
    verbose = "--verbose" in flags

    if live:
        expected = {}
        for c in cases:
            ref = find_ref(c["ref"])
            if not ref:
                continue
            expected[c["name"]] = with_tmp(lambda t: run_shell(ref, c["script"], t))
    else:
        if not os.path.exists(EXPECTED):
            print("no expected.txt - run with --regen first")
            return 2
        expected = load_expected(EXPECTED)

    npass = nfail = nskip = 0
    failures = []

    for c in cases:
        if c["name"] not in expected:
            nskip += 1
            continue

        eo, erc = expected[c["name"]]
        go, grc = with_tmp(lambda t: run_shell(shell, c["script"], t))

        if go == eo and grc == erc:
            npass += 1
            if verbose:
                print("pass  %s" % c["name"])
        else:
            nfail += 1
            failures.append((c, eo, erc, go, grc))
            print("FAIL  %s" % c["name"])

    for c, eo, erc, go, grc in failures:
        print("=" * 68)
        print("case %s   (expectation from %s)" % (c["name"], c["ref"]))
        if c["note"]:
            print("note: %s" % c["note"])
        print("script: %s" % c["script"].replace("\n", "\\n"))
        print("  expected rc=%-4s out=%r" % (erc, eo))
        print("  got      rc=%-4s out=%r" % (grc, go))

    print("\n%d passed, %d failed%s" %
          (npass, nfail, (", %d skipped" % nskip) if nskip else ""))
    return 1 if nfail else 0


if __name__ == "__main__":
    sys.exit(main())
